config/routes.rb
Rails.application.routes.draw do
  root 'short_url_gs#index'
  get 'decode/:short_url' => 'short_url_gs#decode'
  resources :short_url_gs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url_g.rb
class ShortUrlG < ApplicationRecord
	after_create :generate_sort_url

	private
	def generate_sort_url
		p self
		short_url =  get_short_url(self.id)
		self.short_url = short_url
		self.save
	end

  def get_short_url(id)
    alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    temp = id
    short_url=""
    while temp != 0
      short_url = alphabet.slice((temp%62)-1)+short_url
      if (temp % 62) == 0
        temp = temp - 1
      end
      temp=temp/62
    end
    return short_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_url_gs_controller.rb
class ShortUrlGsController < ApplicationController
  before_action :set_short_url_g, only: [:show, :edit, :update, :destroy]

  def decode
    short_url = params[:short_url]
    id = find_id_from_short_url(short_url)
    su = ShortUrlG.find_by_id(id)
    redirect_to su.url

  end
  # GET /short_url_gs
  # GET /short_url_gs.json
  def index
    @short_url_gs = ShortUrlG.all
  end

  # GET /short_url_gs/1
  # GET /short_url_gs/1.json
  def show
  end

  # GET /short_url_gs/new
  def new
    @short_url_g = ShortUrlG.new
  end

  # GET /short_url_gs/1/edit
  def edit
  end

  # POST /short_url_gs
  # POST /short_url_gs.json
  def create
    @short_url_g = ShortUrlG.new(short_url_g_params)

    respond_to do |format|
      if @short_url_g.save
        format.html { redirect_to @short_url_g, notice: 'Short url g was successfully created.' }
        format.json { render :show, status: :created, location: @short_url_g }
      else
        format.html { render :new }
        format.json { render json: @short_url_g.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /short_url_gs/1
  # PATCH/PUT /short_url_gs/1.json
  def update
    respond_to do |format|
      if @short_url_g.update(short_url_g_params)
        format.html { redirect_to @short_url_g, notice: 'Short url g was successfully updated.' }
        format.json { render :show, status: :ok, location: @short_url_g }
      else
        format.html { render :edit }
        format.json { render json: @short_url_g.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /short_url_gs/1
  # DELETE /short_url_gs/1.json
  def destroy
    @short_url_g.destroy
    respond_to do |format|
      format.html { redirect_to short_url_gs_url, notice: 'Short url g was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_short_url_g
      @short_url_g = ShortUrlG.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def short_url_g_params
      params.require(:short_url_g).permit(:url)
    end

    def find_id_from_short_url(short_url)
      alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
      hash=0
      short_url.each_char { |ch|
        hash=(hash*62)+(alphabet.index(ch)+1)
      }
      return hash
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_url_gs_helper.rb
module ShortUrlGsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/short_url_gs/_form.html.erb
<%= form_with(model: short_url_g, local: true) do |form| %>
  <% if short_url_g.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(short_url_g.errors.count, "error") %> prohibited this short_url_g from being saved:</h2>

      <ul>
      <% short_url_g.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/short_url_gs/edit.html.erb
<h1>Editing Short Url G</h1>

<%= render 'form', short_url_g: @short_url_g %>

<%= link_to 'Show', @short_url_g %> |
<%= link_to 'Back', short_url_gs_path %>

app/views/short_url_gs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Short Url Gs</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Short url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @short_url_gs.each do |short_url_g| %>
      <tr>
        <td><%= short_url_g.url %></td>
        <td><%= short_url_g.short_url %></td>
        <td><%= link_to 'Show', short_url_g %></td>
        <td><%= link_to 'Edit', edit_short_url_g_path(short_url_g) %></td>
        <td><%= link_to 'Destroy', short_url_g, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Short Url G', new_short_url_g_path %>

app/views/short_url_gs/new.html.erb
<h1>New Short Url G</h1>

<%= render 'form', short_url_g: @short_url_g %>

<%= link_to 'Back', short_url_gs_path %>

app/views/short_url_gs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @short_url_g.url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= @short_url_g.short_url %>
</p>

<%= link_to 'Edit', edit_short_url_g_path(@short_url_g) %> |
<%= link_to 'Back', short_url_gs_path %>